### ISSUE TITLE
Error in samestr convert

### ISSUE THREAD

**Issue by simeonhebrew** [danielpodlesny/samestr#18]
Hello.

Thank you for this amazing tool.

I've have been running into the same error while using `samestr convert`

```
Traceback (most recent call last):
  File "/home/nthukus/.conda/envs/samestr/bin/kp2np.py", line 64, in <module>
    for line in open(args.map):
FileNotFoundError: [Errno 2] No such file or directory: '/scratchbeta/nthukus/out_convert/CER005_IgApos_S142_R1_001.fastq.gz/CER005_IgApos_S142_R1_001.fastq.gz.contig_map.txt'
Traceback (most recent call last):
  File "/home/nthukus/.conda/envs/samestr/bin/kp2np.py", line 64, in <module>
    for line in open(args.map):
FileNotFoundError: [Errno 2] No such file or directory: '/scratchbeta/nthukus/out_convert/CER210_IgApos_S140_R1_001.fastq.gz/CER210_IgApos_S140_R1_001.fastq.gz.contig_map.txt'
multiprocessing.pool.RemoteTraceback: 
``` 

Would you have any idea as to why I am not able to generate the `contig_map.txt` file?

Thanks.

**Comment by cschu** [comment]
@simeonhebrew just to exclude environment issues -- are you by chance running this from a (self-made) docker/singularity container that does not have access to the `/scratchbeta/` mount? Or running it on a compute node that cannot access the mount?

**Comment by simeonhebrew** [comment]
Hi @danielpodlesny 


Command : 
```
samestr db --mpa-pkl $metaphlan/mpa_vJan21_CHOCOPhlAnSGB_202103.pkl --mpa-markers $metaphlan/mpa_vJan21_CHOCOPhlAnSGB_202103.fna.bz2 --output-dir $SCRATCH/samestr_db_whole

samestr convert --input-files $Control_Pos/*.sam.bz2 --marker-dir $SCRATCH/samestr_db --min-vcov 5 --output-dir $SCRATCH/out_convert_debug --mp-profiles-dir $Tsv_Pos --nprocs 42 --tmp-dir $SCRATCH/temporaryfiles
``` 
This is the original output/error (did a tail of the stdout file):

```
[W::sam_hdr_parse] Duplicated sequence 'VDB|0040-0146-0-0004|M801-c99-c0-c186'
[W::sam_hdr_parse] Duplicated sequence 'VDB|0040-0052-0-0003|M801-c99-c0-c187'
[W::sam_hdr_parse] Duplicated sequence 'VDB|0040-0139-0-0001|M801-c99-c0-c188'
[W::sam_hdr_parse] Duplicated sequence 'VDB|0046-0165-0-0003|M801-c99-c0-c189'
[W::sam_hdr_parse] Duplicated sequence 'VDB|0047-002F-0-0006|M801-c99-c0-c190'
[W::sam_hdr_parse] Duplicated sequence 'VDB|001D-011E-0-0007|M801-c99-c0-c191'
[W::sam_hdr_parse] Duplicated sequence 'VDB|001D-00C7-0-0008|M801-c99-c0-c192'
[W::sam_hdr_parse] Duplicated sequence 'VDB|003B-0000-0-021D|M489-c9-c0-c0'
samtools index: "/scratchbeta/nthukus/out_convert_debug/CER210_IgApos_S140_R1_001.fastq.gz/CER210_IgApos_S140_R1_001.fastq.gz.bam" is in a format that cannot be usefully indexed
samtools index: "/scratchbeta/nthukus/out_convert_debug/CER203_IgApos_S161_R1_001.fastq.gz/CER203_IgApos_S161_R1_001.fastq.gz.bam" is in a format that cannot be usefully indexed
samtools index: "/scratchbeta/nthukus/out_convert_debug/CER005_IgApos_S142_R1_001.fastq.gz/CER005_IgApos_S142_R1_001.fastq.gz.bam" is in a format that cannot be usefully indexed
ooSubprocess: dump_file.py --input_file /scratchbeta/nthukus/sam_files_2/Control_Pos/Control_1/CER209_IgApos_S156_R1_001.fastq.gz.sam.bz2 | filter_sam.py 90 40 | samtools view -bS - | samtools sort - -o CER209_IgApos_S156_R1_001.fastq.gz > /scratchbeta/nthukus/out_convert_debug/CER209_IgApos_S156_R1_001.fastq.gz/CER209_IgApos_S156_R1_001.fastq.gz.bam
samtools index: "/scratchbeta/nthukus/out_convert_debug/CER209_IgApos_S156_R1_001.fastq.gz/CER209_IgApos_S156_R1_001.fastq.gz.bam" is in a format that cannot be usefully indexed
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/nthukus/.conda/envs/samestr/lib/pypy3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/nthukus/.conda/envs/samestr/lib/pypy3.9/site-packages/samestr/convert/sam2bam.py", line 54, in sam2bam
    oosp.ex('samtools', args=['index', arg['bam']], verbose=False)
  File "/home/nthukus/.conda/envs/samestr/lib/pypy3.9/site-packages/samestr/utils/ooSubprocess.py", line 75, in ex
    result = subprocess.check_call(cmd, stdin=in_pipe, **kwargs)
  File "/home/nthukus/.conda/envs/samestr/lib/pypy3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['samtools', 'index', '/scratchbeta/nthukus/out_convert_debug/CER005_IgApos_S142_R1_001.fastq.gz/CER005_IgApos_S142_R1_001.fastq.gz.bam']' returned non-zero exit status 1.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nthukus/.conda/envs/samestr/bin/samestr", line 1018, in <module>
    samestr(args)
  File "/home/nthukus/.conda/envs/samestr/bin/samestr", line 801, in samestr
    cmd_args = parallelize_async(sam2bam, cmd_args, input_args['nprocs'])
  File "/home/nthukus/.conda/envs/samestr/lib/pypy3.9/site-packages/samestr/utils/ooSubprocess.py", line 267, in parallelize_async
    results = [r.get() for r in app_results]
  File "/home/nthukus/.conda/envs/samestr/lib/pypy3.9/site-packages/samestr/utils/ooSubprocess.py", line 267, in <listcomp>
    results = [r.get() for r in app_results]
  File "/home/nthukus/.conda/envs/samestr/lib/pypy3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
subprocess.CalledProcessError: Command '['samtools', 'index', '/scratchbeta/nthukus/out_convert_debug/CER005_IgApos_S142_R1_001.fastq.gz/CER005_IgApos_S142_R1_001.fastq.gz.bam']' returned non-zero exit status 1.

```

**Comment by simeonhebrew** [comment]
@cschu I'm running it from a conda environment and  `/scratchbeta/` is a an allocated server storage directory which is normally accessed by all computing nodes.

**Comment by danielpodlesny** [comment]
hm it looks like the original alignment already has an issue. Did you run this via MetaPhlAn? The `.sam.bz2` seems to contain the 'VDB' markers twice. Did you concatenate the `_SGB` and `_VSG.fna.bz2` files and regenerate the bowtie DBs before running metaphlan by any chance?

**Comment by danielpodlesny** [comment]
It seems that you used an older version of SameStr, so please update to the latest release [1.2024.02](https://github.com/danielpodlesny/samestr/tree/v1.2024.02-1).  Be aware that the [update](https://github.com/danielpodlesny/samestr/tree/v1.2024.02-1?tab=readme-ov-file#recent-updates) comes with a few changes to the command option names. 

We have uploaded SameStr databases generated from MetaPhlAn and mOTUs (which is now also supported) to [Zenodo](https://zenodo.org/communities/samestr) so you can download and use them directly. Simply download the database that matches the one you have used for profiling, extract it, and retry processing with `samestr convert`. This way we can ensure the database is not the problem here. 

If after that you're still running into this problem, please let me know.

**Comment by simeonhebrew** [comment]
I downloaded the SameStr metaphlan database as you guided and run it as follows:

```
samestr convert --input-files $Control_Pos/*.sam.bz2 --marker-dir $SCRATCH/samestr_metaphlan/SameStr_mpa_vJan21_CHOCOPhlAnSGB_202103/db_markers/t__SGB282 --nprocs 16 --tmp-dir $SCRATCH/temporaryfiles --output-dir $SCRATCH/samestresults
``` 

But I got a new error, a bug? `samestr convert` seems to be parsing the database from the output directory.

```
2024-02-12 17:22:22,772 | ERROR | __main__ | samestr | 69 | Aborting. Could not parse database at /scratchbeta/nthukus/samestresults

```

**Comment by simeonhebrew** [comment]
Thanks, got that done.

**Comment by simeonhebrew** [comment]
Thanks, looks like I can access it now but I still have a problem with the generation of `sam` and `bam` files. 


```
2024-02-12 17:51:13,067 | INFO | __main__ | samestr | 62 | Processing data with existing SameStr database based on MetaPhlAn, mpa_vJan21_CHOCOPhlAnSGB_202103
2024-02-12 17:51:13,068 | INFO | __main__ | samestr | 63 | Database contains 108368 files, 27092 clades, 5110862 markers, totalling 8673955580 positions.
/home/nthukus/.conda/envs/samestr/lib/pypy3.9/site-packages/samestr/summarize/read_taxonomic_profiles.py:69: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['relative_abundance'] = pd.to_numeric(df['relative_abundance'], errors='coerce')
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/nthukus/.conda/envs/samestr/lib/pypy3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/nthukus/.conda/envs/samestr/lib/pypy3.9/site-packages/samestr/convert/bam2freq.py", line 61, in bam2freq
    remove(arg['sorted_bam'] + '.bai')
FileNotFoundError: [Errno 2] No such file or directory: '/scratchbeta/nthukus/samestresults/b55_429_IgGneg_S63/b55_429_IgGneg_S63.bam.bai'
```

**Comment by danielpodlesny** [comment]
From this, it's unclear to me what might be the problem. Do you get more specific reporting if you run it with `--verbosity DEBUG`? 

If possible for you, you could share one sample (so both the `sam.bz2` and `profile.txt` files) that fails for you so I could have a look at it. Feel free to reach out via daniel.podlesny<at>embl.de

**Comment by danielpodlesny** [comment]
Following emails, the issue was in the install via pypi and the manual dependency install.

Install through conda resolved everything.
