### ISSUE TITLE
error message in samestr convert

### ISSUE THREAD

**Issue by arimprove59** [danielpodlesny/samestr#26]
I am having difficulties in the samestr convert step. I got the SameStr database from zenodo (SameStr_mpa_vJun23_CHOCOPhlAnSGB_202307.tar.gz; about 6.2 Gb), placed it in an empty samestr_db folder which I created, and tried:
samestr convert --input-files [path to my sam.bz2 files]/*sam.bz2 --marker-dir samestr_db/ --min-vcov 5 --output-dir out_convert/

I am getting the error message: ERROR | __main__ | samestr | 69 | Aborting. Could not parse database at out_convert/
Any input is appreciated!

**Comment by danielpodlesny** [comment]
Just to make sure the database is set up correctly: After downloading the database from Zenodo, have you unzipped it with `tar -xzvf SameStr_mpa_vJun23_CHOCOPhlAnSGB_202307.tar.gz`? You should point `--marker-dir` to the untared/zipped directory.

**Comment by arimprove59** [comment]
Thank you. I managed to run the steps all the way through samestr summarize where I am getting the following error message. My taxa profile files have a format like xyz_profiled.txt. So I did: 
samestr summarize --input-dir out_compare_fmt/ --tax-profiles-dir profiles_fmt/ --tax-profiles-extension "_profiled.txt" --marker-dir /home/arashidi/samestr_db2/SameStr_mpa_vJun23_CHOCOPhlAnSGB_202307 --output-dir out_summarize_fmt/

2024-05-16 00:30:10,616 | INFO | samestr.summarize.summarize | summarize | 48 | Reading SameStr data from out_compare_fmt/
2024-05-16 00:30:10,618 | INFO | samestr.summarize.read_samestr_data | read_samestr_data | 101 | Merging matrix for 565 clades.
Traceback (most recent call last):
  File "/home/arashidi/miniconda3/bin/samestr", line 338, in <module>
    samestr(args)
  File "/home/arashidi/miniconda3/bin/samestr", line 308, in samestr
    cmd_args = serialize(summarize, [input_args])
  File "/home/arashidi/miniconda3/lib/python3.9/site-packages/samestr/utils/ooSubprocess.py", line 276, in serialize
    results.append(func(arg))
  File "/home/arashidi/miniconda3/lib/python3.9/site-packages/samestr/summarize/summarize.py", line 62, in summarize
    cooc_data.iloc[:, 2:] = cooc_data.iloc[:, 2:].mask(
  File "/home/arashidi/.local/lib/python3.9/site-packages/pandas/core/indexing.py", line 911, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/home/arashidi/.local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1942, in _setitem_with_indexer
    self._setitem_with_indexer_split_path(indexer, value, name)
  File "/home/arashidi/.local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1977, in _setitem_with_indexer_split_path
    self._setitem_with_indexer_frame_value(indexer, value, name)
  File "/home/arashidi/.local/lib/python3.9/site-packages/pandas/core/indexing.py", line 2073, in _setitem_with_indexer_frame_value
    self._setitem_single_column(loc, val, pi)
  File "/home/arashidi/.local/lib/python3.9/site-packages/pandas/core/indexing.py", line 2133, in _setitem_single_column
    self.obj._mgr.column_setitem(
  File "/home/arashidi/.local/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 1335, in column_setitem
    col_mgr.setitem_inplace(idx, value)
  File "/home/arashidi/.local/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 2044, in setitem_inplace
    super().setitem_inplace(indexer, value)
  File "/home/arashidi/.local/lib/python3.9/site-packages/pandas/core/internals/base.py", line 357, in setitem_inplace
    value = np_can_hold_element(arr.dtype, value)
  File "/home/arashidi/.local/lib/python3.9/site-packages/pandas/core/dtypes/cast.py", line 1877, in np_can_hold_element
    if element._hasna:
  File "/home/arashidi/.local/lib/python3.9/site-packages/pandas/core/generic.py", line 6299, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute '_hasna'

**Comment by arimprove59** [comment]
Same exact error message, unfortunately.

**Comment by danielpodlesny** [comment]
I see - something seems to go wrong during merging of the tax. profiles and strain comparison data. Could you please:

1. rerun the command with `samestr --verbosity DEBUG summarize --input...` etc. 
2. open a random file in `out_compare_fmt/` and `profiles_fmt/` to confirm the file names still have the same format?

**Comment by arimprove59** [comment]
Sure. I appreciate your help. 
1. I get following, and then the same error message as last time. 
3     zr15702_216  zr15702_220               1              2             4             4             10             9              10            10
4     zr15702_216  zr15702_221               1              3             3             5              5             7               5             5
...           ...          ...             ...            ...           ...           ...            ...           ...             ...           ...
3398   zr16701_74    zr16701_8               1              6             9            11             17            16              18            17
3399   zr16701_74    zr16701_9               1              5             9            10             18            22              19            18
3400   zr16701_75    zr16701_8               1              6            12            14             20            21              26            24
3401   zr16701_75    zr16701_9               2              5            10            11             19            23              25            23
3402    zr16701_8    zr16701_9               1              5             8             8             14            20              19            19

[3403 rows x 10 columns]
2024-05-16 01:28:27,016 | INFO | samestr.summarize.summarize | summarize | 48 | Reading SameStr data from out_compare_fmt/
2024-05-16 01:28:27,019 | INFO | samestr.summarize.read_samestr_data | read_samestr_data | 101 | Merging matrix for 565 clades.

2. When I open a random file in out_compare_fmt/, the names don't have the _profiled.txt but those in profiles_fmt/ do.

**Comment by danielpodlesny** [comment]
I'm not sure what is causing this. Luckily the last step is already quite compressed in size - would you be able to share a zipped version of your `profiles_fmt/` and `out_compare_fmt/ ` [via email](mailto:daniel.podlesny@embl.de)? then I could take a look

**Comment by arimprove59** [comment]
Thank you. Just sent you those files by email.
